apiVersion: v1
kind: Pod
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  containers:
    - name: gitea
      image: gitea/gitea:latest
      env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: LOCAL_ROOT_URL
          value: http://gitea-clusterip:3000/
        - name: ROOT_URL
          value: https://gitea-99.arriaga.eu/
        - name: DISABLE_SSH
          value: "true"
        - name: DB_TYPE
          value: mysql
        - name: DB_HOST
          value: mariadb-clusterip:3306
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: mariadb-database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: mariadb-user
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: mariadb-password
      volumeMounts:
        - name: gitea-data
          mountPath: /data
      ports:
        - containerPort: 3000
  volumes:
    - name: gitea-data
      persistentVolumeClaim:
        claimName: gitea-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-clusterip
spec:
  type: ClusterIP
  selector:
    app: gitea
  ports:
    - targetPort: 3000  # endpoint
      port: 3000      # clusterip
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-ingress
spec:
  rules:
    - host: gitea-99.arriaga.eu
      http:
        paths:
          - path: /
            pathType: Prefix  # Exact
            backend:
              service:
                name: gitea-clusterip
                port:
                  number: 3000
