apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
stringData:
  mariadb-root-password: "12345Abcde"
  mariadb-database: "gitea"
  mariadb-user: "gitea"
  mariadb-password: "12345Abcde"
